name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk: [8, 11, 17, 21, 25]
        os: [ubuntu-22.04, windows-latest]
        browser: ["${{ vars.E2E_TEST_BROWSER }}"]
        experimental: [false]
        test-suffix: [release, snapshot]
        include:
          - jdk: 25
            os: macos-14
            browser: chrome
            experimental: true
            test-suffix: release
          - jdk: 25
            os: macos-14
            browser: chrome
            experimental: true
            test-suffix: snapshot
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v7
        id: coursier-cache
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{ matrix.jdk }}
          apps: sbt
      - uses: actions/setup-node@v6
        with:
          node-version: 24.10.0
      - name: Enable Corepack
        run: corepack enable
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        env:
          E2E_TEST_BROWSER: ${{ matrix.browser }}
        with:
          run: sbt scalafmtSbtCheck scalafmtCheckAll test "${{ steps.coursier-cache.outputs.cache-hit-coursier && 'scripted' || 'scriptedSequentialPerModule' }}${{ matrix.jdk == 8 && format(' sbt-scalajs-esbuild/*-{0} sbt-scalajs-esbuild-electron/basic-project-{0} sbt-scalajs-esbuild-electron/e2e-test-playwright-node-{0} sbt-scalajs-esbuild-electron/electron-builder-{0}', matrix.test-suffix) || format(' */*-{0}', matrix.test-suffix) }}"
