name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'
jobs:
  build:
    strategy:
      matrix:
        jdk: [8, 11]
        os: [ubuntu-latest, windows-latest]
        experimental: [false]
        include:
          - jdk: 11
            os: macos-14
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
        id: coursier-cache
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{ matrix.jdk }}
          apps: sbt
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Enable Corepack
        run: corepack enable
      - name: Setup yarn
        run: corepack prepare yarn@1.22.19 --activate
      - name: Setup pnpm
        run: corepack prepare pnpm@8.8.0 --activate
      - name: Compile
        if: ${{ matrix.jdk == 8 }}
        run: sbt Test/compile
      - name: Run tests
        if: ${{ matrix.jdk == 11 }}
        uses: coactions/setup-xvfb@v1
        with:
          run: sbt scalafmtSbtCheck scalafmtCheckAll test ${{ steps.coursier-cache.outputs.cache-hit-coursier && 'scripted' || 'scriptedSequentialPerModule' }}
