name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk: [8, 11, 17, 21]
        os: [ubuntu-22.04, windows-latest]
        browser: ["${{ vars.E2E_TEST_BROWSER }}"]
        experimental: [false]
        include:
          - jdk: 11
            os: macos-14
            browser: chrome
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v6
        id: coursier-cache
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{ matrix.jdk }}
          apps: sbt
      - uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - name: Enable Corepack
        run: corepack enable
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        env:
          E2E_TEST_BROWSER: ${{ matrix.browser }}
        with:
          run: sbt scalafmtSbtCheck scalafmtCheckAll test "${{ steps.coursier-cache.outputs.cache-hit-coursier && 'scripted' || 'scriptedSequentialPerModule' }}${{ matrix.jdk == 8 && ' sbt-scalajs-esbuild/* sbt-scalajs-esbuild-electron/basic-project sbt-scalajs-esbuild-electron/e2e-test-playwright-node sbt-scalajs-esbuild-electron/electron-builder' || '' }}"
